# INST414 — Lab 6: Regression + Evaluation (OLS vs Logistic)

In this lab you will:
- create an outcome for whether someone is rearrested within 1 year,
- fit an **OLS (linear probability)** model and a **logistic regression** model using `sklearn`,
- convert predicted probabilities to predicted labels using a **threshold** (we’ll use the base rate),
- compute **TPR (recall)** and **PPV (precision)**,
- and see how the logistic regression regularization parameter `C` affects performance.

Lab tasks at the end extend this to a *violent rearrest* outcome and explore average predictions by group (sex/race).

**Before you start:** Click **File → Save a copy in Drive** so you have your own version of this notebook. If you skip this step, your work will not be saved.

**Turn off AI assistance:** Go to **Settings → AI Assistance** and uncheck everything. AI-generated code is not allowed on assignments in this course.

# Load modules and settings

In [34]:
import pandas as pd

pd.options.display.max_columns = None
pd.options.display.max_rows = 20

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import numpy as np
np.set_printoptions(legacy='1.25')

# Part 1 — Load data

In [35]:
universe = pd.read_csv('https://www.dropbox.com/scl/fi/5wg86ttvvx9cu15zn8xae/lab7_inst414.csv?rlkey=d9qinlmgn0q2n5qzrw8jib314&dl=1')
universe['filing_date'] = pd.to_datetime(universe.filing_date)
universe.head()

,arrest_id,person_id,filing_date,age_at_arrest,sex,race,charge_degree_felony,num_arr_last_year,offense_category_drug,offense_category_property,offense_category_violent,num_prop_arr_last_2yrs
0,4150651,3245369,2018-03-20,29.117808,M,Black,True,3.0,False,True,False,1.0
1,7518413,589868,2016-01-30,26.394521,M,Black,True,1.0,True,False,False,0.0
2,6709912,910296,2016-08-24,28.830137,M,Black,True,1.0,False,False,True,0.0
3,4951609,2849904,2017-10-25,44.254795,M,White,False,0.0,False,False,False,0.0
4,7444510,2539404,2016-02-20,28.115068,F,White,False,0.0,True,False,False,0.0

In [36]:
arrest_events = pd.read_csv('https://www.dropbox.com/scl/fi/wv9kthwbj4ahzli3edrd7/arrest_events_lab6.feather?rlkey=mhxozpazqjgmo6qqahc2vd0xp&dl=1')
arrest_events['filing_date'] = pd.to_datetime(arrest_events.filing_date)
arrest_events.head()

   person_id  arrest_id filing_date charge_degree offense_category
0      78786    3835604  2018-05-01        felony         property
1      78786   11999735  2018-05-01        felony         property
2    1064849    3442497  2018-07-12   misdemeanor            other
3      78786    4205882  2018-03-09        felony         property
4      78786   12006352  2018-03-09        felony         property

**Note:** The `universe` table is already a *modeling table* (one row per current arrest) and includes engineered features such as `charge_degree_felony` and `num_arr_last_year` from earlier labs.

The `arrest_events` table contains event-level rows that we’ll use to create outcomes (rearrest within 1 year).

In [37]:
def tpr_ppv(df, y_col='y', yhat_col='yhat'):
    """Return TPR and PPV as conditional probabilities."""
    tpr = df.loc[df[y_col] == 1, yhat_col].mean()
    ppv = df.loc[df[yhat_col] == 1, y_col].mean()
    return {'TPR': float(tpr), 'PPV': float(ppv)}

# Part 2 — Create outcome (rearrest within 1 year)

In [38]:
temp_df = universe[['person_id', 'arrest_id', 'filing_date']].merge(arrest_events,
                                                                    on=['person_id'],
                                                                    how='left',
                                                                    suffixes=['_univ', '_arr'])
temp_df.shape

(1156, 7)

## Step 1 — Keep rearrests within 1 year

We want rearrests that happen **after** the current arrest and **within one year**.

In the merged temporary table, `filing_date_univ` is the universe (current) date and `filing_date_arr` is the event date.

In [39]:
temp_df = temp_df[temp_df.filing_date_arr.between(temp_df.filing_date_univ + pd.DateOffset(days=1),
                                                  temp_df.filing_date_univ + pd.DateOffset(years=1))]
temp_df.head()
temp_df.shape

,person_id,arrest_id_univ,filing_date_univ,arrest_id_arr,filing_date_arr,charge_degree,offense_category
65,1026471,5693666,2017-06-01,4327311.0,2018-02-15,misdemeanor,other
70,1026471,5693666,2017-06-01,5449706.0,2017-07-26,misdemeanor,drug
196,46047,3094523,2018-08-31,2832896.0,2018-10-19,misdemeanor,other
206,46047,3094523,2018-08-31,2640835.0,2018-11-26,felony,other
288,65834,3091885,2018-08-31,2830864.0,2018-10-19,felony,property

(30, 7)

## Step 2 — Ensure the event is after the current arrest

We exclude same-day / earlier events so we don’t accidentally count the current arrest as a ‘rearrest’.

## Step 3 — Create the outcome column in `universe`

If a universe `arrest_id` appears in the filtered temp table, that person had at least one rearrest within 1 year.

We create `outcome_any_arrest` as a boolean outcome (True/False).

In [40]:
universe['outcome_any_arrest'] = universe.arrest_id.isin(temp_df.arrest_id_univ)

universe.head()

,arrest_id,person_id,filing_date,age_at_arrest,sex,race,charge_degree_felony,num_arr_last_year,offense_category_drug,offense_category_property,offense_category_violent,num_prop_arr_last_2yrs,outcome_any_arrest
0,4150651,3245369,2018-03-20,29.117808,M,Black,True,3.0,False,True,False,1.0,False
1,7518413,589868,2016-01-30,26.394521,M,Black,True,1.0,True,False,False,0.0,False
2,6709912,910296,2016-08-24,28.830137,M,Black,True,1.0,False,False,True,0.0,False
3,4951609,2849904,2017-10-25,44.254795,M,White,False,0.0,False,False,False,0.0,False
4,7444510,2539404,2016-02-20,28.115068,F,White,False,0.0,True,False,False,0.0,False

Compute the base rate (share rearrested within 1 year):

In [41]:
universe['outcome_any_arrest'].mean()

0.007

# Part 3 — OLS (linear probability) baseline

We fit an OLS model where the prediction is interpreted as a probability estimate. This is sometimes called a **linear probability model**.

(It can predict values below 0 or above 1; that’s one reason logistic regression is often preferred.)

In [42]:
ols_model = LinearRegression()

Then, create a list that has the names of the columns we want for features.

In [43]:
universe.columns

Index(['arrest_id', 'person_id', 'filing_date', 'age_at_arrest', 'sex', 'race',
       'charge_degree_felony', 'num_arr_last_year', 'offense_category_drug',
       'offense_category_property', 'offense_category_violent',
       'num_prop_arr_last_2yrs', 'outcome_any_arrest'],
      dtype='object')

In [44]:
features = ['charge_degree_felony', 'num_arr_last_year']
universe[features]

     charge_degree_felony  num_arr_last_year
0                    True                3.0
1                    True                1.0
2                    True                1.0
3                   False                0.0
4                   False                0.0
..                    ...                ...
995                  True                0.0
996                  True                0.0
997                 False                2.0
998                 False                4.0
999                 False                5.0

[1000 rows x 2 columns]

In [45]:
ols_model = ols_model.fit(X=universe[features], y=universe['outcome_any_arrest'])

We will now look at the $\beta$s (Betas)/coefficients

In [46]:
ols_model.intercept_
ols_model.coef_

0.0011465397032531487

array([0.00212199, 0.00472281])

Now we will predict

In [47]:
universe['pred_ols'] = ols_model.predict(X=universe[features])
universe.head()

,arrest_id,person_id,filing_date,age_at_arrest,sex,race,charge_degree_felony,num_arr_last_year,offense_category_drug,offense_category_property,offense_category_violent,num_prop_arr_last_2yrs,outcome_any_arrest,pred_ols
0,4150651,3245369,2018-03-20,29.117808,M,Black,True,3.0,False,True,False,1.0,False,0.017437
1,7518413,589868,2016-01-30,26.394521,M,Black,True,1.0,True,False,False,0.0,False,0.007991
2,6709912,910296,2016-08-24,28.830137,M,Black,True,1.0,False,False,True,0.0,False,0.007991
3,4951609,2849904,2017-10-25,44.254795,M,White,False,0.0,False,False,False,0.0,False,0.001147
4,7444510,2539404,2016-02-20,28.115068,F,White,False,0.0,True,False,False,0.0,False,0.001147

## Compute performance metrics
First, we will set the threshold to be the outcome rate.

In [48]:
base_rate = universe['outcome_any_arrest'].mean()

universe['y'] = universe['outcome_any_arrest'].map({True: 1, False: 0})
universe['yhat'] = (universe['pred_ols'] > base_rate).map({True: 1, False: 0})

tpr_ppv(universe, y_col='y', yhat_col='yhat')

{'TPR': 0.8571428571428571, 'PPV': 0.018867924528301886}

Let's compute the True Positive Rate.

In [49]:
# TPR (Recall)
universe.loc[universe['y'] == 1, 'yhat'].mean()

0.8571428571428571

Let's compute the Positive Predictive Value

In [50]:
# PPV (Precision)
universe.loc[universe['yhat'] == 1, 'y'].mean()

0.018867924528301886

# Part 4 — Train/test split (out-of-sample evaluation)

We split into train and test sets and evaluate performance on the test set. We stratify so the base rate is similar in both splits.

In [51]:
train, test = train_test_split(
    universe,
    test_size=0.5,
    shuffle=True,
    stratify=universe['outcome_any_arrest'],
    random_state=0,
)

train.shape, test.shape

((500, 16), (500, 16))

Stratifying by the outcome means that both train and test sets should have equal (or very similar) base rates.

In [52]:
train['outcome_any_arrest'].mean()
test['outcome_any_arrest'].mean()

0.008

0.006

### Run OLS model on train

In [53]:
ols_model = ols_model.fit(X=train[features], y=train['outcome_any_arrest'])

In [22]:
ols_model.intercept_
ols_model.coef_

np.float64(-0.00408212172240675)

array([0.00887594, 0.0054045 ])

In [23]:
test = test.copy()

test['pred_ols'] = ols_model.predict(test[features])
test[['pred_ols']].head()

     pred_ols
122 -0.004082
777  0.004794
794  0.004794
63   0.010198
183  0.004794

In [24]:
base_rate_train = train['outcome_any_arrest'].mean()

test['y'] = test['outcome_any_arrest'].map({True: 1, False: 0})
test['yhat'] = (test['pred_ols'] > base_rate_train).map({True: 1, False: 0})

tpr_ppv(test, y_col='y', yhat_col='yhat')

{'TPR': 0.6666666666666666, 'PPV': 0.013888888888888888}

In [25]:
# TPR (test)
test.loc[test['y'] == 1, 'yhat'].mean()

np.float64(0.6666666666666666)

In [26]:
# PPV (test)
test.loc[test['yhat'] == 1, 'y'].mean()

np.float64(0.013888888888888888)

# Part 5 — Logistic regression

Logistic regression outputs probabilities in (0, 1).

`C` controls regularization strength: larger `C` = weaker regularization; smaller `C` = stronger regularization.

In [27]:
logistic_model = LogisticRegression(C=0.1, max_iter=2000)

In [28]:
logistic_model = logistic_model.fit(X=train[features], y=train['outcome_any_arrest'].astype(int))

In [29]:
test['pred_logistic'] = logistic_model.predict_proba(test[features])[:, 1]
test[['pred_logistic']].head()

     pred_logistic
122       0.005697
777       0.006074
794       0.006074
63        0.007264
183       0.006074

In [30]:
test['yhat'] = (test['pred_logistic'] > base_rate_train).map({True: 1, False: 0})

tpr_ppv(test, y_col='y', yhat_col='yhat')

{'TPR': 0.6666666666666666, 'PPV': 0.020618556701030927}

In [31]:
# TPR (logistic, test)
test.loc[test['y'] == 1, 'yhat'].mean()

np.float64(0.6666666666666666)

In [32]:
# PPV (logistic, test)
test.loc[test['yhat'] == 1, 'y'].mean()

np.float64(0.020618556701030927)

# Lab Tasks (in class)

## Task 1 — Logistic regression with a different `C`

Repeat logistic regression on the **training set** with `C = 10`, then evaluate on the test set.

- Fit `LogisticRegression(C=10, max_iter=2000)` on `train[features]`
- Predict probabilities for `test` into `pred_logistic2`
- Create `yhat2` using the **training base rate** (`base_rate_train`) as the threshold
- Compute TPR and PPV for `yhat2`
- Which value of `C` gives better performance, and why might that happen?

In [ ]:
# ### CODE HERE ###

## Task 2 — New outcome: violent rearrest within 1 year

Create `outcome_violent_arrest`: True if the person has **any rearrest** within 1 year where `offense_category == 'violent'`.

Hint: reuse the `temp_df` logic, but filter the rearrest events to violent before creating the `isin` outcome.

In [ ]:
# ### CODE HERE ###

## Task 3 — Predict violent rearrest (OLS)

Create a new train/test split (stratify on `outcome_violent_arrest`) and run OLS using predictors:
- `charge_degree_felony`
- `num_arr_last_year`
- `offense_category_violent`
- `num_prop_arr_last_2yrs`

Then predict on the test set, threshold using the **training base rate**, and compute TPR and PPV.

In [ ]:
# ### CODE HERE ###

## Task 4 — Average prediction by sex

Using the model from Task 3, compute the average predicted probability by sex: $E[\,\widehat{P}(y=1)\mid sex\,]$.

Which sex gets higher predictions on average?

In [ ]:
# ### CODE HERE ###

## Task 5 — Average prediction by race

Using the model from Task 3, compute the average predicted probability by race: $E[\,\widehat{P}(y=1)\mid race\,]$.

Which race gets higher predictions on average?

In [ ]:
# ### CODE HERE ###